### PR TITLE
fix TestCaseWithSave for parent class

### LINKED ISSUE #259: TestWithSave does not work for common parent class
If `assertEqualWithSave(this,test_obj)` is invoked from common test class (e.g. in Horace, `test_gen_sqw_accumulate_sqw_mex` and `test_gen_sqw_accumulate_sqw_nomex`  are testing the same code with different parameters, so both are the children of `gen_sqw_accumulate_sqw_common` class and the constructor of the particular classes just sets appropriate parameters, the method does not recognizes the class name and fails. 

This is simple bug which should be fixed.

### PR DESCRIPTION
**Pull request by abuts**
fixes #259

### CODE REVIEW

File: _test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/TestCaseWithSave.m [hunk 1]
```diff
@@ -641,6 +641,8 @@ function assertMethodWithSave (this, var, var_name, funcHandle, varargin)
                         strncmpi(cont{end},'test',4)
                     test_name = cont{end};
                     break
+                else
+                    test_name = cont{end};
```
Comment (nickbattam-tessella) [inline _test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/TestCaseWithSave.m:645]: The `if` and `else` block perform the same action. Is that check required?

Comment (nickbattam-tessella) [reply _test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/TestCaseWithSave.m:645]: Looking again the `break` is different in two branches, so it can be rewritten with just that in the `if`
```
test_name = cont{end};
if strcmp && ~strcmp && strncmpi
  break;
end
```

Comment (abuts) [reply _test/shared/matlab_xunit_ISISextras/@TestCaseWithSave/TestCaseWithSave.m:638]: yes -- this is better
