### PR TITLE
multifit settings

### LINKED ISSUE #245: Setting multiple foreground functions in multifit fails
the code:
```
            ds1 = IX_dataset_1d();
            ds2 = IX_dataset_1d();            
            mfc=mfclass(ds1,ds2);
            funs = {@(x,p)(1+p*x),@(x,p)(p+x.^2)};
            mfc = mfc.set_fun(funs);
```
fails
This is certainly a bug.

### PR DESCRIPTION
**Pull request by abuts**
fixes #245. Should fix the bug with multiple foreground function settings

### CODE REVIEW

File: herbert_core/applications/multifit/@mfclass/private/set_fun_private_.m [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+end
+
+% Trivial case of no input arguments; just return without doing anything
+if numel(args)==0
+    ok = true;
+    mess = '';
+    return
+end
+
+% % Check there is data
```
Comment (nickbattam-tessella) [inline herbert_core/applications/multifit/@mfclass/private/set_fun_private_.m:37]: Commented out/dead  code block

File: herbert_core/applications/multifit/@mfclass/private/set_fun_private_.m [hunk 2]
```diff
@@ -0,0 +1,122 @@
+function [ok, mess, obj] = set_fun_private_ (obj, isfore, args)
```
Comment (nickbattam-tessella) [inline herbert_core/applications/multifit/@mfclass/private/set_fun_private_.m:1]: The PR is showing this as a new file. 

There is existing an existing `set_fun_private_(...)` method defined in `mfclass`:  `herbert_core/applications/multifit/@mfclass/set_fun_private_.m` which is amended but not removed on this PR.

**Review by nickbattam-tessella — CHANGES_REQUESTED** [review]

File: herbert_core/applications/multifit/@mfclass/private/set_fun_private_.m (hunk 2 above)
Comment (abuts) [reply herbert_core/applications/multifit/@mfclass/private/set_fun_private_.m:1]: yes, it should be deleted. It have probably been erroneously saved from Matlab editor
