### PR TITLE
fix noisify bugs #234, extend interface for paging

### LINKED ISSUE #234: Noisify returns std deviations, not variances, and incorrectly checks for empty input error.
General consensus is that the error part of [signal, error] in PixelData is a variance.

Currently noisify (herbert_core\utilities\math) returns standard deviations, by constructing variances for the noise added to the signal and then taking their square root (LL.52, 57). Additionally at L.52, the input variance is treated as a standard deviation and is squared before combining with the noise contribution.

Additional problem with this function is that at L.50 the input error is checked for existence and for being empty; at L.51 the sizes of the input and noise errors are checked to be equal. This looks like the wrong way round - the check should be against NOT empty.

### PR DESCRIPTION
**Pull request by cmarooney-stfc**
This PR does the following:

- it does fix #234 to correct 
    - (i) interpretation of the input e and output eout as standard deviations rather than variances - sqrts and ^2s are removed
    - (ii) isempty test on the error output processing at the end is switched to not isempty to allow correct comparison of input and output error sizes

- it also supports a fourth argument to pass a previously calculated max signal value to replace the locally calculated one. This allows a max to be calculated in a previous pass when paging is used.
    - the existing interface is unchanged
    - if the fourth argument is present, the third argument can be defaulted using a value <0.

### CODE REVIEW

File: herbert_core/utilities/maths/noisify.m [hunk 1]
```diff
@@ -25,32 +34,44 @@
...
+        ymax = max(abs(y(:)));          % find maximum magnitude of y for arbitrary dimensions
     end
-    ymax = max(abs(y(:)));          % find maximum magnitude of y for arbitrary dimensions
     dy=(fac*ymax)*randn(size(y));   % st. dev. of randn is sigma=1
     yout=y+dy;
     eout=ones(size(y))*(fac*ymax)^2;
 end
 
-if exist('e','var') && isempty(e)
+% this code now outputs a variance to be consistent between the use of eout
```
Comment (nickbattam-tessella) [inline herbert_core/utilities/maths/noisify.m:65]: I don't think these two comments are adding any value for future developers:
- to anyone reading the code as it is now you have defined e as a variance at the top; so they wouldn't expect or think it was an stddev
- the missing `~` was a bug you've fixed. We don't need to document that beyond the git log

**Review by nickbattam-tessella — COMMENTED** [review]
.

File: herbert_core/utilities/maths/noisify.m [hunk 2]
```diff
@@ -25,32 +34,44 @@
...
             yout(i)=randpoisson(abs(y(i)));
         end
-        eout=abs(y);  % the inpuy y is the mean and variance of the Poisson distribution
+        eout=abs(y);  % the input y is the mean and variance of the Poisson distribution
     else
         error('Unrecognised random sampling distribution')
     end
-else
-    if nargin==3
+else % 3rd arg did not exist or was not a distribution name
```
[the remark this answers is not in the document]
Comment (hsautessella) [reply herbert_core/utilities/maths/noisify.m:41]: You'll want to use [Matlab's `inputParser`](https://www.mathworks.com/help/matlab/ref/inputparser.html) if you're adding named arguments

**Comment by cmarooney-stfc** [comment]
Recommitted to avoid defaulting fac with maxval present.

NB did not update header comments for this, more later.

**Comment by cmarooney-stfc** [comment]
Recommitted to avoid defaulting fac with maxval present.

This commit does not use the parse_args method as I could not see how to work this with fac optionally not present.

File: herbert_core/utilities/maths/noisify.m (hunk 1 above)
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:80]: Cleaned up with commit 4

File: herbert_core/utilities/maths/noisify.m (hunk 2 above)
[the remark this answers is not in the document]
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m]: Fac made optional, 'maxval' flag introduced with commit 3. Not using input parser as optional fac gets in the way - for the one flag, alternative method used.

File: herbert_core/utilities/maths/noisify.m [hunk 3]
```diff
@@ -17,40 +17,69 @@
...
+%           Omitting factor will use the default value 0.1.
+%
+%   If no input errors, e, just set e=[]. Note that eout will be created
+%   regardless of whether e is present, so the first overload output is
+%   probably incomplete.
+
+% deal with optional arguments
+is_poisson= false;
+fac = 0.1;
+if nargin>=2
```
Comment (hsautessella) [inline herbert_core/utilities/maths/noisify.m:36]: Is this `if` statement necessary? Do you not get the same behaviour by removing this `if` block and making the call on line 38 `addOptional`?

File: herbert_core/utilities/maths/noisify.m [hunk 4]
```diff
@@ -17,40 +17,69 @@
...
+    p = inputParser;
+    addRequired(p,'y');   % y compulsory
+    addRequired(p,'e');   % e compulsory if any of remaining optional/parameter arguments present
+    numeric_or_string = @(x) isnumeric(x) || ischar(x);
+    addOptional(p,'dist_or_factor',fac, numeric_or_string);  % fac (numeric) or distribution ('poisson') optional, default to fac=0.1
```
Comment (hsautessella) [inline herbert_core/utilities/maths/noisify.m:41]: I'd put this block in a function at the bottom of the file e,g:
```matlab
function [y, e, dist_or_factor, maximum_value] = parse_args(y, e, varargin)
   ...
end
```

File: herbert_core/utilities/maths/noisify.m [hunk 5]
```diff
@@ -17,40 +17,69 @@
...
+    addParameter(p,'maximum_value',-999,@isnumeric);  % ymax, as parameter 'maximum_value'. Default to highly visible negative value.
```
Comment (hsautessella) [inline herbert_core/utilities/maths/noisify.m:42]: Could the default here be `max(y)` rather than -999?

File: herbert_core/utilities/maths/noisify.m [hunk 6]
```diff
@@ -17,40 +17,69 @@
...
+        error('3rd argument cannot be interpreted as a Gaussian factor or legal probability distribution')
     end
+end
+
+% Use Poisson distribution and ignore other arguments
+if is_poisson
+    yout=zeros(size(y));
+    for i=1:numel(y)
+        yout(i)=randpoisson(abs(y(i)));
+    end
```
Comment (hsautessella) [inline herbert_core/utilities/maths/noisify.m:63]: `y` could be a large array. Can this operation be vectorized? E.g.
```matlab
yout = randpoisson(abs(y))
```

File: herbert_core/utilities/maths/noisify.m [hunk 7]
```diff
@@ -17,40 +17,69 @@
...
-    if is_stringmatchi(varargin{1},'poisson')
-        yout=zeros(size(y));
-        for i=1:numel(y)
-            yout(i)=randpoisson(abs(y(i)));
-        end
-        eout=abs(y);  % the inpuy y is the mean and variance of the Poisson distribution
+    % vary if 'poisson' or fac present
+    if isnumeric(p.Results.dist_or_factor)
+        fac = p.Results.dist_or_factor;
+    elseif p.Results.dist_or_factor == 'poisson'
```
Comment (hsautessella) [inline herbert_core/utilities/maths/noisify.m:51]: Matlab has a [`strcmp`](https://www.mathworks.com/help/matlab/ref/strcmp.html) function that's usually used to compare strings. We may even consider `strcmpi` so the comparison is not case-sensitive

File: herbert_core/utilities/maths/noisify.m [hunk 8]
```diff
@@ -17,40 +17,69 @@
...
+%   regardless of whether e is present, so the first overload output is
+%   probably incomplete.
+
+% deal with optional arguments
+is_poisson= false;
+fac = 0.1;
+if nargin>=2
+    p = inputParser;
+    addRequired(p,'y');   % y compulsory
+    addRequired(p,'e');   % e compulsory if any of remaining optional/parameter arguments present
```
Comment (hsautessella) [inline herbert_core/utilities/maths/noisify.m:39]: Should we have a `@isnumeric` validator here?

**Review by hsautessella — CHANGES_REQUESTED** [review]

File: herbert_core/utilities/maths/noisify.m [hunk 9]
```diff
@@ -17,40 +17,69 @@
...
-        end
-        eout=abs(y);  % the inpuy y is the mean and variance of the Poisson distribution
+    % vary if 'poisson' or fac present
+    if isnumeric(p.Results.dist_or_factor)
+        fac = p.Results.dist_or_factor;
+    elseif p.Results.dist_or_factor == 'poisson'
+        is_poisson = true;
     else
-        error('Unrecognised random sampling distribution')
+        error('3rd argument cannot be interpreted as a Gaussian factor or legal probability distribution')
```
Comment (hsautessella) [inline herbert_core/utilities/maths/noisify.m:54]: `error` also [takes an error ID argument](https://www.mathworks.com/help/matlab/ref/error.html#d122e350173). We've been trying to be more consistent in including identifiers in all our errors now. Having an identifier makes it easier to catch particular error types.

The identifier should have form `'CLASSNAME:method_name'`. Since this is a free function, I'd make the identifier `HERBERT:noisify`.

File: herbert_core/utilities/maths/noisify.m (hunk 5 above)
Comment (nickbattam-tessella) [reply herbert_core/utilities/maths/noisify.m:42]: If we can avoid introducing magic numbers it would be preferable.

File: herbert_core/utilities/maths/noisify.m (hunk 8 above)
Comment (nickbattam-tessella) [reply herbert_core/utilities/maths/noisify.m:39]: `e` is optional, but positionally significant. If you define it as required does the parser raise an error when it's missing?

Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:39]: e is required at that point in the code as it is within a nargin>=2 block, so it will never be missing as coded. Having e and disp_or_fac as both optional is problematic, hence the restriction. I tried isnumeric(y) in the debugger and it worked so I could add that.

File: herbert_core/utilities/maths/noisify.m (hunk 3 above)
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:36]: We then have 2 optional parameters e and disp_or_fac with the possibility that e gets omitted and disp_or_fac does not. This is not a supported option from the header comments and I don't think I want to start choosing between optional parameters. If there are more than 2 parameters then e should be required. Ideally disp_or_fac should be a named parameter but that changes the existing interface.

File: herbert_core/utilities/maths/noisify.m (hunk 8 above)
Comment (hsautessella) [reply herbert_core/utilities/maths/noisify.m:39]: Why is it problematic if `e` and `disp_or_fac` are both optional?

File: herbert_core/utilities/maths/noisify.m (hunk 5 above)
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:42]: If max(y) is done here then it will be wasted cpu time for the poisson case (also it is max(abs(y(:)))). I can name the parameter - -999 was a distinctive visual value, its only effect here is to be negative and not difficult to read like -1. What I can do is name the constant in addition so it is not so much a magic number.

File: herbert_core/utilities/maths/noisify.m (hunk 3 above)
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:36]: There are also suggestions in the code that Toby would prefer e=[] rather than omitting it.

File: herbert_core/utilities/maths/noisify.m (hunk 6 above)
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:63]: Guessing that since it is churning out random numbers, the generator is being advanced at each call. So not vectorizable. The equivalent built-in poissrnd does not seem to have this.

File: herbert_core/utilities/maths/noisify.m (hunk 3 above)
Comment (hsautessella) [reply herbert_core/utilities/maths/noisify.m:36]: The `addOptional` function adds a positional argument - so there's no way that one could specify `disp_or_fact` and not `e`.

File: herbert_core/utilities/maths/noisify.m (hunk 5 above)
Comment (hsautessella) [reply herbert_core/utilities/maths/noisify.m:42]: Good point - I hadn't spotted we weren't using it in the Poisson case. Would `-inf` be an even more obvious negative value?

File: herbert_core/utilities/maths/noisify.m (hunk 3 above)
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:36]: This is not clear. All the inputParser docs say is that, combined with your/Nick's suggested code, is that e and disp_or_fac are both optional. I don't see how this form of argument parsing prevents leaving out e and using disp_or_fac - it will depend on the validation for e. It doesn't look like the normal method of arguments with defaults (ie optionals) where the first n optional arguments match.

File: herbert_core/utilities/maths/noisify.m (hunk 5 above)
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:42]: That's a useful alternative. My measure of obvious/distinctive is "hits the eye of the beholder". Guessing that -999 is more "visual" than the string -inf - this is what you will see in the debugger. I was holding off using -666. But I would combine this with a named variable, I have coded USE_LOCAL_MAX to be visually distinctive in the code as distinct from the debugger.

File: herbert_core/utilities/maths/noisify.m (hunk 8 above)
Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:39]: As said above, you could leave out e and include disp_or_fac. I don't see anything in the inputParser docs which suggest this is impossible - it seems that ignoring it is done partly on the basis of the validation function argument, which will skip the argument slot if not validated and move on to the next one.

File: herbert_core/utilities/maths/noisify.m (hunk 3 above)
Comment (hsautessella) [reply herbert_core/utilities/maths/noisify.m:36]: Ah, you're right. I'd misunderstood the parser. I hadn't realised you could also specify parameters added via `addOptional` as named arguments.

File: herbert_core/utilities/maths/noisify.m [hunk 10]
```diff
@@ -17,40 +17,75 @@
...
+    p = inputParser;
+    addRequired(p, 'y', @isnumeric);   % y compulsory
+    addRequired(p, 'e', @isnumeric);   % e compulsory if any of remaining optional/parameter arguments present
+    numeric_or_poisson = @(x) isnumeric(x) || strcmpi(x,'poisson');
+    addOptional(p, 'dist_or_factor', fac, numeric_or_poisson);  % fac (numeric) or distribution ('poisson') optional, default to fac=0.1
+    addParameter(p,'maximum_value', use_local_max, @isnumeric);  % ymax, as parameter 'maximum_value'. Default to highly visible named negative value.
+    parse(p,y,e,varargin{:});
+
+    % pick up signal max value as either default or input
+    ymax = p.Results.maximum_value;
```
Comment (nickbattam-tessella) [inline herbert_core/utilities/maths/noisify.m:81]: Rather than pass a magic number as the maxval in as an argument, you could define that as a local (function level) magic number and move the    
```
if ymax == USE_LOCAL_MAX
        ymax = max(abs(y(:)));
end
```
block into this function.

Then the caller will have the correct value for maximum without needing any additional logic.

Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:80]: Pushed to do this. Now changed flag to -inf after consideration of existence of negative y values as per previous conversations.

File: herbert_core/utilities/maths/noisify.m [hunk 11]
```diff
@@ -17,40 +17,79 @@
...
         yout=zeros(size(y));
         for i=1:numel(y)
             yout(i)=randpoisson(abs(y(i)));
         end
-        eout=abs(y);  % the inpuy y is the mean and variance of the Poisson distribution
+        eout=abs(y);  % the input y is the mean and variance of the Poisson distribution
     else
-        error('Unrecognised random sampling distribution')
+        if ~ymax_calculated
+            ymax = max(abs(y(:)))
```
Comment (nickbattam-tessella) [inline herbert_core/utilities/maths/noisify.m:51]: this logic is repeated in the `parse_args` function. I see who it is needed here for `nargin == 1`. 

Can the `parse_args` function be adapted to handle that case too so the `ymax_calculated` flag and repeated logic are not required?

Comment (cmarooney-stfc) [reply herbert_core/utilities/maths/noisify.m:51]: Undoubtedly, but this is working now, and the next work with noisify in Horace depends on it, so that improvement will happen later.
